library verilog;
use verilog.vl_types.all;
entity MEGA_Sorokin_SM is
    port(
        z1              : out    vl_logic;
        x1              : in     vl_logic;
        y1              : in     vl_logic;
        z2              : out    vl_logic;
        x2              : in     vl_logic;
        y2              : in     vl_logic;
        z3              : out    vl_logic;
        x3              : in     vl_logic;
        y3              : in     vl_logic;
        z4              : out    vl_logic;
        x4              : in     vl_logic;
        y4              : in     vl_logic;
        z5              : out    vl_logic;
        x5              : in     vl_logic;
        y5              : in     vl_logic;
        z6              : out    vl_logic;
        x6              : in     vl_logic;
        y6              : in     vl_logic;
        z7              : out    vl_logic;
        x7              : in     vl_logic;
        y7              : in     vl_logic;
        z8              : out    vl_logic;
        x8              : in     vl_logic;
        y8              : in     vl_logic;
        z9              : out    vl_logic;
        x9              : in     vl_logic;
        y9              : in     vl_logic;
        z11             : out    vl_logic;
        x10             : in     vl_logic;
        y10             : in     vl_logic;
        x11             : in     vl_logic;
        y11             : in     vl_logic;
        z12             : out    vl_logic;
        x12             : in     vl_logic;
        y12             : in     vl_logic;
        z13             : out    vl_logic;
        x13             : in     vl_logic;
        y13             : in     vl_logic;
        z10             : out    vl_logic;
        z14             : out    vl_logic;
        x14             : in     vl_logic;
        y14             : in     vl_logic;
        z15             : out    vl_logic;
        x15             : in     vl_logic;
        y15             : in     vl_logic;
        z_cout          : out    vl_logic
    );
end MEGA_Sorokin_SM;
